baseURL = "https://lokal.ninja/brandenburg"
languageCode = "de-DE"
title = "Lokal Ninja - Brandenburg"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Brandenburg"
  repo = "brandenburg"
